[project]
name = "rescue-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.135.3",
    "flask>=3.1.2",
    "flask-cors>=6.0.2",
    "google-genai>=1.62.0",
    "httpx>=0.27.0",
    "livekit-agents[cartesia,deepgram,elevenlabs,google,groq,openai,silero,turn-detector]~=1.5",
    "livekit-plugins-noise-cancellation~=0.2",
    "livekit-plugins-upliftai==1.2.8",
    "loguru>=0.7.3",
    "numpy>=1.24.0",
    "onnxruntime>=1.20.0",
    "passlib>=1.7.4",
    "psycopg2-binary>=2.9.11",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.1",
    "python-jose>=3.5.0",
    "python-socketio[asyncio]>=5.11.0",
    "sqlalchemy>=2.0.49",
    "transformers>=4.40.0",
    "uvicorn>=0.44.0",
]

[tool.setuptools]
packages = []
